### ISSUE TITLE
Gulp doesn't work with reactify 1.1.1

### ISSUE THREAD

**Issue by marioglsub** [fedosejev/react-essentials#141]
Using the following gulpfile.js file in Chapter 1: 

var gulp = require('gulp');
var browserify = require('browserify');
var reactify = require('reactify');
var source = require('vinyl-source-stream');

gulp.task('default', function () {
    return browserify('./source/app.js')
        .transform(reactify)
        .bundle()
        .pipe(source('snapterest.js'))
        .pipe(gulp.dest('./build/'));
}); 

and the dipendencies ...

  "devDependencies": {
    "browserify": "^16.2.3",
    "gulp": "^4.0.0",
    "reactify": "^1.1.1",
    "vinyl-source-stream": "^2.0.0"
  }

i get the error shown below:
Using gulpfile ~\source\repos\snapterest\gulpfile.js                                                                                        Starting 'default'...                                                                                                                                                   'default' errored after 29 ms                                                                                                                                                Error: Cannot find module 'C:\Users\mario\source\repos\snapterest\source\app.js' from 'C:\Users\mario\source\repos\snapterest' at C:\Users\mario\source\repos\snapterest\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21 at load (C:\Users\mario\source\repos\snapterest\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)at onex (C:\Users\mario\source\repos\snapterest\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31) at C:\Users\mario\source\repos\snapterest\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47 at FSReqWrap.oncomplete (fs.js:154:21)
